eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8799
spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      routes:
      - id: api-a
        uri: http://localhost:8762
        predicates:
        - Path=/api-a/**
        filters:
        - StripPrefix=1
      - id: api-b
        uri: lb://SERVICE-FEIGN
        predicates:
        - Path=/api-b/**
        filters:
        - StripPrefix=1

